apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  namespace: apps
type: Opaque
stringData:
  mongodb-root-password: rootpassword
  mongodb-username: root
  mongodb-passwords: flashcardspassword
  mongodb-database: flashcards
