replicas: 1 # Single StatefulSet replica for lab

resources: # Resource requests and limits for the pod
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

volumeClaimTemplate: # Storage request for the ES data volume
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi