apiVersion: v2
name: flashcards-app
description: Flashcards REST API application
type: application
version: 1.0.0
appVersion: "v1.0.8"


dependencies:
  - name: mongodb
    version: 18.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled