apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-tls
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    # paste your actual TLS certificate here
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    # paste your actual private key here
    -----END PRIVATE KEY-----
