apiVersion: v1
kind: Secret
metadata:
  name: flashcards-gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  type: git
  url: "https://gitlab.com/portfolio5815640/flashcards-gitops.git"
  username: "Lielik"
  password: "glpat-b2-p_gGD61_5F13pkj9vMm86MQp1OmhtN3dqCw.01.120qdupk5"
