{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mongo-credentials",
    "namespace": "databases",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mongo-credentials",
        "namespace": "databases",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "mongodb-passwords": "AgBXzh2CGs0wOVvb2wWA6w5bNX4iSQ8fSDdA6quFEWD+rZrvze9E7JFE6FDOK3Pr0dZurusGQWjp1bkuVCiqD6hn/VAigHzUGdx+aaok1dq5rwbkmyMUJG4pVN0SQ7gtMf4eHs3179zZeMpO6Avw+uTk88j8n69dg6T6/eCX0xejowzvTBBN7Bd6iCXOc6aKPlaD/ZWlCOPUMEakUnp5zl5m9XFXKgZZ2GndzVE/SI+2Y6+gVP3VyyFAmXOAeY3XOMvJQddot7qOPokPrFN2Ixc1frMfSts7DRa679Ml95kHGHV+pfbF3yu1g9IA6oetrDSmlx5n97e+U4qt1nAcg8HgsPzZubiqTvKXzqK2WVMbm33xG1Ucnd9+6S0VOuF6Ag9QCUS4N4iAQjUaTcqfju1oVQNp/vE+YfQe4HWUY2nbSuGcdFRUQlHl4sEPTMUupYq1zlt2GPUPoNS3joxop9VX5BiubGJQbexT0aSy/82ixtxUPoUDZbEPNW7cr0iP0CwANLa3EDJu6u9WEKQKEyXJJEvfdObcAETL+q12//P7RHkC7XRR2oPt0Vy06jA4wlcOjlSvU4WiUkTZrz20r/SrKcT9zsLakwFFv39Oh/tMRJCK3T4ARf1sA/iyZJlJYPEKfKVsyJvVfEHtzJFNCi4+GUzms2QeRU+u+Bvf0gRwaTtc7tI96mnotzWiklvdXDbrIAjI4wW9v3I=",
      "mongodb-root-password": "AgBldFAasuqRU/7j4rJn39JOquVMyQ2MqIeijXP3zJZFzPesjjsgIZY45y7axnKK6zXurWrc0YaH5jLR320OugtBhFN1hYBXfUp0R1QmBODwfQuwWFuOR+iJLsAQRipZlxkKDJBETje2Tg6oLQB4GfttmtjDbNvVOTvkHRJFSIncXb5h09mXXiHrTWscU11cfyQ7Pl/1QzA5Z9id8REWy1c8qOCXZ/DSJLYTlCCCRxCf1Nlj8O30bxRwlLbJWaDwugTPept0dGw30xrNvyn51bI/NXk82qLfm/cYtmN4+JgYnZQfJPjqb5536xxw/2Emw+wSHYHXE+FMQ2egkae015PTMGNmfTXGXaewThmocpZ+SgaApsCpSWsJmLmXMrSG+LX7LyQ2Yhz96KQRiXJCf5AnbF6SnjWB9cJ19PK6mRNyS5WQPVTSmC2oaHUxlj2WhmNGjk6pc+RqspzONJ9sadpuVc0RzG3/FNTGNyQSZ5d+6mvxcrJw3vYdVRi2zNOfRtPJHKRk66jPDdaRAH1QycwLudfUvdcC0UotqRVqekvaX1/aZiYqe2HwfEJX/SkW2IlNZRGH4n75XHBb03y9KMr2IuCkfTz+Rx/9YHfO2I8rnVXu9bzjxijjkRGbaZh7Bds/JFxgcnIa7mbepFO9z6+BFLKGxQS2zd1l4ciltDJeoz7LO7yIdVxOvtAaod43kG3uwJlKCuPMJPQ="
    }
  }
}
