{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mongo-uri",
    "namespace": "apps",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mongo-uri",
        "namespace": "apps",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "uri": "AgC6tcgzBZ5HrUr1l3v8unw00OZlINqcOnh3+tlhrEGQN9rc5aK6uHvUWsfThRb0mqrwL/QN4NlTiNXzalQMt2d+dBOrLsl/AquEI90UtZKzvpCUYhAaL2AFMC5dQm1isy2WEjIgKasmS2YzIrLT1hUFWFBHZ7V6++U0yU4G3uWsFGUX5tA1g8K6r7tN+Svpz7L/DgIt3fUKnQ/59hELe1pPQ2Gcmkgrld0+sbJNNBqOeNogNT0qxf6j35cwCw8I3gxqRVGVbIYrkaJ6aj+00V1LeMm3bsBS9Kc3H3tc20ntTBOD3lurWqgXOnEwQeg77VSVbQ1NSwqKBTp8zfuTElVVtyzJMJUWQlO7IbVgAwkYMFvPcWpjJFwZx7LWzwviRk6JYoN34m34DJ1uIw5ck5YwF5x99iTpXJJVjZAlj4U4EjYNeQFoDdMkEKygVAbMpTtw36etpJmCW3g83hHNFkeg7TO26gDUoaQfmY6ry9cyZlgD/m/FUgbnipUPniHoBG8mGsLZHnkYKbbtjCdo3nlLpzC2abZR3Kez8R/pO2svT8kfqgMUMWZPPhau6Hkbl4jU08Y56QsOA59f/I6YOSafaOVCI0hgvldJaYxouwyu1VvC8YxEXFbpFYTqtkTy6SldMSTmPeBcu6w5reUU+/xY61uV1Ean38JjI7MNrvIr+gnESpjE9K0FVyB6uRbQs3Dp6Wua6PA7pjAQJZ9JsHDPZWQHe+Duc3HQwYIRcE/9A3zkTqeKI0kWkdfWDDlsiocn/mQOlFmZ8CoxP+SYIOCZVC01UXVz6MSiqsKovle9kuMHRo525/RFFfVtXo3LEHEP/Smpqvrp6kU="
    }
  }
}
