apiVersion: v2
name: kibana
description: Kibana Helm chart for the logging stack
type: application
version: 1.0.0

dependencies:
  - name: kibana
    repository: https://helm.elastic.co
    version: 8.5.1
