# The Elasticsearch service endpoint that Kibana connects to for reading/writing data.
elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200" # ES-k8s-service-name:default-ES-port

# Accept self-signed ES cert in the lab
kibanaConfig:
  kibana.yml: |
    elasticsearch.ssl.verificationMode: none

service:
  type: ClusterIP #  Expose Kibana only inside the cluster because we use ingress

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi