apiVersion: v2
name: fluentbit
description: Fluent Bit Helm chart for forwarding logs to Elasticsearch
type: application
version: 1.0.0

dependencies:
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.54.0