apiVersion: v2
name: umbrella
description: Umbrella chart that includes flashcards, mongodb, etc
version: 0.1.0
dependencies:
  - name: flashcards
    version: 0.1.0
    repository: "file://charts/flashcards"
  - name: mongodb
    version: 15.6.10
    repository: "https://charts.bitnami.com/bitnami"
