# charts/umbrella/values.yaml

global:
  awsAccountId: "473959757606"

flashcards:
  image:
    repository: "{{ .Values.global.awsAccountId }}.dkr.ecr.ap-south-1.amazonaws.com/flashcards-app"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 2

  service:
    type: ClusterIP
    port: 80
    targetPort: 5000

  ingress:
    enabled: true
    className: nginx
    host: flashcards.portfoio.com    
    path: /
    tls: []

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

  envFromSecret:
    enabled: true
    name: mongo-uri    
    key: uri          

  readinessProbe:
    path: /health
    port: 5000
  livenessProbe:
    path: /health
    port: 5000

mongodb:
  architecture: standalone
  auth:
    enabled: true
    existingSecret: "mongo-credentials"
    usernames:
      - "flashcards_user"
    databases:
      - "flashcards"
  primary:
    persistence:
      enabled: true
      size: 2Gi
  fullnameOverride: "mongodb"   
