---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDMebjDvsG2iaH+hLaJMSeXCY67oFxF6adC6VHwOD+oAXaC2kCgqxw0Z2CQn5HvWGPTYwiD50A8eOiSG6k8MS00EhKv3vwbSdizume5VpIGWv30rC1pC5qgKT+9FFYDIE6Z7WZsuYxEqJ0KX7bhc+l0w1A/PIzTXMy57rXiZy8zeKoUKmgw85rzMWtDVfXNC3WI8ndDcqULknRLfTFajtPuX/o3PLa6mmHPXkr4EKt2YR6XAmuCgdlItfWT1tkQDZzW5t8W9fQuShqeDcR+5CCTSbltstlFR2iqyGNmZ8qKJr7qLiFpGq0Sws/RqPJNcTXMQBbcKcghZ2/i6/dun/IskFe7tQTOVt0xnjD5dRV+jz/opVhClfm8u5JlNDQ6L9jrsys9bC/Invz8rkx+s8FG1hYL+r1IxJj0ee7DF8UhM9vnRgnr0WutwbD3a2DhVABKC5/o/q0S5pmn3GeaCo9St3EOvk8MHO2UqLEyrJUKzjJeEPTEF8plT42l3z8hAk7H4C8DrAQRhdwOQn61uj7Y3B+ZoURN+DxPmdKiqIQnY9KlMRqcYmI4+yUYFFnYd4B2hl4NwzkNzl1KG9ELEDsWJGQgbgctRNCUyMCqeuu8VV6CP8NHZMcyC86UYjEeTNdNejSnTBHBxUglnYQv+R8EFDffj8491QRr1d6Fmc5R1VDH6o17UHVyXaqlib5U4Zmx+WIen357r1GNtEPEOVDMUOkZZqEMotRdbk796QXRPgZr/pXnwbsY+AvIkwHYOeXbTZA2VzPrtZw96en35gTkZGktbKIcyQqvs/IAPXvX51RW3/m6QoSFft0k/K7Yy/0l5SWpnQXjwRzbOSZ89Qg9SWDW3IMLBoZZHihcR5ZTw7nDlTfwIN8oy8mxRD4PBm0RlJCEnieU3QDnJ6SKhVCSr1IqTww22Cea61tgwhNT
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare
