apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-credential-helper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Lielik/flashcards-gitops
    targetRevision: main
    path: platform/ecr-credential-helper
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
