elasticsearch:
  replicas: 1

  esJavaOpts: "-Xmx512m -Xms512m"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 10Gi

  extraEnvs:
    - name: cluster.initial_master_nodes
      value: ""
    - name: discovery.seed_hosts
      value: ""

  esConfig:
    elasticsearch.yml: |
      discovery.type: single-node
      xpack.security.enabled: false

  createCert: false
