apiVersion: v1
kind: Service
metadata:
  name: {{ include "flashcards.fullname" . }}-api
  namespace: {{ .Values.namespace | default "apps" }}
  labels:
    {{- include "flashcards.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "flashcards.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
{{- define "flashcards.fullname" -}}
{{- .Chart.Name }}-{{ .Release.Name }}
{{- end }}

{{- define "flashcards.labels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "flashcards.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}