---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-uri
  namespace: apps
spec:
  encryptedData:
    uri: AgCR8OnXebqrGfbZPDApQqkKyd3CR9i/fVxy+SCjDHmjqTxLfTWzcMjZRQUl2avUb3TMny3tGjc7U80MNu+5nKcE1n8Ahm2t0GmLypmV9z4iNxHLDcnkwVI6aQ+Cj85KCVG1A9KPxtYk7YdUiGNkjpHDlgHa88nvFSQ6QH0knR/ShXcB45qPsl/dNCduAFHozUFClt/pB+C4Kx8+poMIJQyCeZK9u5yN/uGUfJjrxCNhEAmrc+9eCvv3tRx3AFW7law1p/kEHv5P5aF7//XukmGeAlMXzcZ66j6ftKurUOF6YezBz7jDP4bLJmpKNp7/nQDYCC8v7olSQAln1cDXE8a6hY1dwMus5jq7zAQLy60Ix89JygBiylD06vDca62P3ZC0bx2m3fPCAtTazdjxJjIKd3Dvf6wqEGxmY5UqpWmCH34TvyZU9otmSzROT29b99OezKIy0pYTmMJf1wRwWl5w6HWNcPYjK7MUys0wlh7GVFKhE/Sr+th6yae4BO8PYenip+tpkjOYVO4yqDAJVaKa74xj9GxcU8NG6dExjgUpEXiV+9LS28MT40S/wUqJ4hntIH/Otkn2WGF+SHJeo77DCYYukMEDdjjuDRZcfXDWxDOwi88+xX8DZTXranyF60/JTIiJWHLX56AoPmVsCChsrhtYoE57jKWrHy6jC3ugmSxTYQujr7ODpq/R/AlG69O1fFHwT8xXYww501FPQymrv2xdNUTWapq8qlbr0M7DqTFb7odnkBbaJJi+Dr7hEvPZPtN4x0u6ABRFPxXbaAiQqMsFwcnDkL0MpuPg6L7DYP31mS5HCxkMMu5ojYHgW6rTrrii0Ved
  template:
    metadata:
      creationTimestamp: null
      name: mongo-uri
      namespace: apps
    type: Opaque
