---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-uri
  namespace: apps
spec:
  encryptedData:
    uri: AgB9m7qR7Wj+gOKHo/F9cihkksjixTodyyv/7Xz+MSvPW9LBtTfcCUA+AP8N5Er1/YIkWqQXvhrKc0tVvsH/jwybmHPjlKSVJbBwvtmstgEOhY0Iaf3Mkh/7kQH8mvkdvX22HMqt1FsASD87WFxo03F52zkSiO4nEWkMb9tvsPqAukNVheXH4kwSUijv2dWX7MFctbYnDq9K8usEOKbDUBwbB3deTFHX9pd1yZX/yrigdi7/xDAGv70R6ov9FtjFwWpEnZ19N9TLOJ9tlp2+ICSrCj4Rq3Ymq8JUo0Rjh4/QjPLEEXpFaFh4dobi/HBMUL9jpT3LsaNUsjNlosWet7zY94+5KZXSgAS/Djb0NQEAaTcrrsDTHSQhcuiKlnXYo42Y8l49BGnh1um+Qe7G6IlgIjM1fpAK/8po0fHIfouVHG3RiRJgbBsHae7qWey3+QGjAo9M++/ofcfljhIECs4Ls9wN95+7rKmDNfaWjQGxAskXRcZqtCSMjjjCcsSwRS17pNRRj42rZkxXA7UowykyMCNf7c4i4AbrCpqQsm2J9JYdeUH0PpCpo4k5QJzWSJ2lSPpnxhqklIJKCKlkoHQhg17SRtS8UHihHkfUqvghPbXrGRU+9K/PQZtqL+iTD3mM0jrrq8l1HAsqznz9x7eshvkg4cmkyz6tUhfJNFH+aLCYiNmddjBWzin8XrvVAg3+aufAjyCrq33Ffeph6pdMHZYtYo0ncQJ5lkarO/BJrt43RXR+Ag8PpdiwJv4gl7K1elHvJuxz4/qRdFGnba8PJ13mDKS5vqRgzalBLL9tMcxJNJt3B3uc+Yg7uw==
  template:
    metadata:
      name: mongo-uri
      namespace: apps
    type: Opaque
