global:
  image:
    tag: v2.12.2

crds:
  install: true

applicationSet:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.portfolio.com
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.portfolio.com
