apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
spec:
  project: portfolio-apps
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.6.0
    helm:
      valueFiles:
        - ../argo/argocd-values.yaml
      values: |
        server:
          ingress:
            enabled: true
            hosts:
              - argocd.portfolio.com
            tls:
              - secretName: argocd-server-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
