image:
  repository: ""            # e.g. 4739....amazonaws.com/flashcards-app
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: flashcards.portfolio.com   
  path: /
  tls: []                   

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongo-uri
        key: uri

readinessProbe:
  path: /health
  port: 5000
livenessProbe:
  path: /health
  port: 5000
