---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: apps
spec:
  encryptedData:
    secret-key: AgA+quvB57oYx/eEyENOzGNglTJ4nsEDWyeRoWbZ3sZ8QjjEg1snNWqLD4nBdaA4q+t/mEXRIE7J9I1yRCAHDw9OURbe2zOxp1TqmY8n3ihgPgSZGmCfoB/EcMR2lEmaQNbdGPqhbbGDmtDs8y2UgKTchbpewKJfM1dno7iB+fccIoyz40hy259hSgOBpmDfRI3yOd/+ZaXvowBabgahUHHqtpxkuVt9nqDsbOU1PNeiFPN0BLU/9XW4mVP/cfS0F6z70oe1++Q1P3x5hqk9sgI1t7J6A+ifId91DdacGMz35vLrXy3pbWJ2gweBMb6hgrC9M7LeCnPZLG0An1Ba2W5+NS+m+fhfhjDWwm5q4PaPuUIdbmgzMlgAT6hHQLxQe9WHIpohXSixEtc75yZiCBhfny0nj35ccegS0UCZW50UerL6r5LOWBRrYaSMIVf28M7kZefu6Jme74obqELknHJAtQ7pmlPHI5SO/Dp2Qcj90LTkoRc4vcqlASNlHhibyy+9CjIiQcwITRnPfhefw/JOkHpkSmUBaq4CERBhdM1gep5VdOfvuEVybAmX2jVsGo7FLdAtMRcQVh6LjgdQxvLyjjYVRfRiPcRMXhFP6prOMticFgC5/Li1KcYpd3LGLvy39nxgqq3jLEadvtuLouELKYyiEdTss48EQHsJ4U6S+YUaYwx3uVALbhMHt06Rcr+cScBEUHq+4S8eHKYsBwMm8++M+Z8eKpK/fR2m2PsDafNWRd879BxQviRlmlblxA1ryPMaTg==
  template:
    metadata:
      name: flask-secret
      namespace: apps
