# Child Application: deploys MongoDB using the Bitnami Helm chart, using a pre-created SealedSecret for credentials
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: portfolio-apps
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.10
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: true
          existingSecret: "mongo-credentials"
          usernames:
            - "flashcards_user"
          databases:
            - "flashcards"
        persistence:
          enabled: true
          size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
